# Generated by Django 6.0.3 on 2026-03-20 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('discount_percent', models.PositiveIntegerField(verbose_name='Chegirma (%)')),
                ('applicable_plan', models.CharField(default='all', max_length=20, verbose_name="Qo'llaniladigan tarif")),
                ('max_uses', models.PositiveIntegerField(default=100, verbose_name='Maksimal foydalanish')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Foydalanilgan')),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kupon',
                'verbose_name_plural': 'Kuponlar',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name="To'lov ID")),
                ('external_id', models.CharField(blank=True, max_length=200, verbose_name='Tashqi tizim ID (PayMe/Click)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Summa ($)')),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Muvaffaqiyatli'), ('failed', 'Rad etildi'), ('cancelled', 'Bekor qilindi'), ('refunded', 'Qaytarildi')], default='pending', max_length=15, verbose_name='Holat')),
                ('method', models.CharField(choices=[('payme', 'PayMe'), ('click', 'Click'), ('uzcard', 'Uzcard'), ('humo', 'Humo'), ('visa', 'Visa'), ('stripe', 'Stripe')], max_length=15, verbose_name='Usul')),
                ('plan', models.CharField(choices=[('pro_monthly', 'Pro (oylik)'), ('pro_yearly', 'Pro (yillik)'), ('team', 'Jamoa')], max_length=15, verbose_name='Tarif')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='Karta (oxirgi 4)')),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('failure_code', models.CharField(blank=True, max_length=100, verbose_name='Xato kodi')),
                ('failure_msg', models.TextField(blank=True, verbose_name='Xato xabari')),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('original_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.coupon')),
                ('refunded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_processed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('last_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
            },
        ),
    ]
