# Generated by Django 6.0.3 on 2026-03-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='community/files/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='post',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='community/videos/%Y/%m/'),
        ),
    ]
