# Generated by Django 6.0.3 on 2026-03-20 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='📚', max_length=10, verbose_name='Emoji')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('short_desc', models.CharField(max_length=300, verbose_name='Qisqa tavsif')),
                ('icon', models.CharField(default='📚', max_length=10)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/')),
                ('access_type', models.CharField(choices=[('free', 'Bepul'), ('pro', 'Pro')], default='free', max_length=10)),
                ('difficulty', models.CharField(choices=[('beginner', "Boshlang'ich"), ('intermediate', "O'rta"), ('advanced', 'Yuqori')], default='beginner', max_length=15)),
                ('duration_hours', models.PositiveIntegerField(default=0, verbose_name='Davomiylik (soat)')),
                ('language', models.CharField(default='uz', max_length=10, verbose_name='Til')),
                ('tags', models.CharField(blank=True, max_length=300, verbose_name='Teglar')),
                ('is_published', models.BooleanField(default=False, verbose_name='Nashr etilgan')),
                ('is_coming_soon', models.BooleanField(default=False, verbose_name='Tez kunda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yozilish',
                'verbose_name_plural': 'Yozilishlar',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib')),
                ('lesson_type', models.CharField(choices=[('text', 'Matn'), ('video', 'Video'), ('text_video', 'Matn + Video'), ('interactive', 'Interaktiv')], default='text', max_length=15)),
                ('access_type', models.CharField(choices=[('free', 'Bepul'), ('pro', 'Pro')], default='free', max_length=10)),
                ('content', models.TextField(blank=True, verbose_name='Matn kontent (HTML)')),
                ('duration_minutes', models.PositiveIntegerField(default=10, verbose_name='Davomiylik (daq)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='lessons/videos/%Y/%m/', verbose_name='Video fayl')),
                ('video_duration', models.PositiveIntegerField(default=0, verbose_name='Video davomiylik (soniya)')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='lessons/thumbnails/')),
                ('is_published', models.BooleanField(default=True, verbose_name='Nashr etilgan')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_desc', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('ai_content', models.TextField(blank=True, verbose_name='AI uchun mazmun (admin tomonidan kiritiladi)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Savol')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizlar',
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Variant matni')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('order', models.PositiveIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.quiz')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('video_watched_seconds', models.PositiveIntegerField(default=0)),
                ('quiz_passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progresses', to='courses.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('quiz_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.quizoption')),
            ],
            options={
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
    ]
