# Generated by Django 6.0.3 on 2026-03-20 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('brute_force', 'Brute Force'), ('suspicious_reg', "Shubhali ro'yxat"), ('bot_detected', 'Bot aniqlandi'), ('ip_blocked', 'IP Bloklandi'), ('sql_injection', 'SQL Injection urinishi'), ('xss_attempt', 'XSS Urinishi'), ('other', 'Boshqa')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('critical', 'Kritik')], default='medium', max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xavfsizlik hodisasi',
                'verbose_name_plural': 'Xavfsizlik hodisalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_type', models.CharField(choices=[('registered', "Ro'yxatdan o'tgan"), ('guest', 'Mehmon'), ('suspicious', 'Shubhali'), ('blocked', 'Bloklangan')], default='guest', max_length=15)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('referrer', models.URLField(blank=True, verbose_name='Qayerdan keldi')),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('path', models.CharField(max_length=500, verbose_name='Sahifa URL')),
                ('method', models.CharField(default='GET', max_length=10)),
                ('status_code', models.PositiveIntegerField(default=200)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobil'), ('desktop', 'Kompyuter'), ('tablet', 'Planshet'), ('bot', 'Bot')], default='desktop', max_length=10)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('user_agent', models.TextField(blank=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('risk_reason', models.CharField(blank=True, max_length=200)),
                ('is_vpn', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sahifa tashrifi',
                'verbose_name_plural': 'Sahifa tashrif kuzatuvi',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address'], name='analytics_p_ip_addr_384afc_idx'), models.Index(fields=['path'], name='analytics_p_path_3fa0ca_idx'), models.Index(fields=['created_at'], name='analytics_p_created_9ccd2b_idx'), models.Index(fields=['visitor_type'], name='analytics_p_visitor_a69d1d_idx')],
            },
        ),
    ]
