# Generated by Django 6.0.3 on 2026-03-20 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_or_domain', models.CharField(max_length=255, unique=True, verbose_name='Email yoki domen (*@domen.com)')),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bloklangan email',
                'verbose_name_plural': 'Bloklangan emaillar',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('success', models.BooleanField(default=False, verbose_name='Muvaffaqiyatli')),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Login urinishi',
                'verbose_name_plural': 'Login urinishlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Familiya')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Avatar')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=10, verbose_name='Tarif')),
                ('pro_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Pro tarif tugash sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Xodim')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloklangan')),
                ('block_reason', models.TextField(blank=True, verbose_name='Bloklash sababi')),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('streak_count', models.PositiveIntegerField(default=0, verbose_name='Streak')),
                ('last_activity', models.DateField(blank=True, null=True, verbose_name='Oxirgi faollik')),
                ('max_streak', models.PositiveIntegerField(default=0, verbose_name='Eng uzun streak')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Joylashuv')),
                ('website', models.URLField(blank=True, verbose_name='Vebsayt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxat sanasi")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP manzil')),
                ('reason', models.TextField(blank=True, verbose_name='Sabab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloklangan IP',
                'verbose_name_plural': 'Bloklangan IP lar',
            },
        ),
    ]
